drop table if exists users cascade;
drop table if exists student cascade;
drop table if exists instructor cascade;
drop table if exists ga cascade;
drop table if exists administrator cascade; 
drop table if exists accounts cascade;
drop table if exists courses cascade;
drop table if exists notes cascade;
drop table if exists assignments cascade;
drop table if exists assistant;
drop table if exists teaches;
drop table if exists enrolled;
drop table if exists course_assignments;
drop table if exists course_notes;
drop table if exists ga_create_assignment;
drop table if exists ga_create_note;
drop table if exists instructor_create_assignment;
drop table if exists instructor_create_note;
drop table if exists submitted_assignments;
drop table if exists make_account;
drop table if exists useful_links;
drop table if exists announcements;
drop table if exists course_assignment_types;
drop table if exists session;
drop table if exists useful_links;
drop table if exists announcements;
