drop table users cascade;
drop table student cascade;
drop table instructor cascade;
drop table ga cascade;
drop table administrator cascade; 
drop table accounts cascade;
drop table courses cascade;
drop table notes cascade;
drop table assignments cascade;
drop table assistant;
drop table teaches;
drop table enrolled;
drop table course_assignments;
drop table course_notes;
drop table ga_create_assignment;
drop table ga_create_note;
drop table instructor_create_assignment;
drop table instructor_create_note;
drop table submitted_assignments;
drop table ga_grade;
drop table instructor_grade;
drop table make_account;